<?php



/**
 * This class defines the structure of the 'car' table.
 *
 *
 * This class was autogenerated by Propel 1.6.9 on:
 *
 * Tue 03 Sep 2013 04:11:14 PM EEST
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.cron_project.model.map
 */
class CarTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.cron_project.model.map.CarTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('car');
        $this->setPhpName('Car');
        $this->setClassname('Car');
        $this->setPackage('lib.cron_project.model');
        $this->setUseIdGenerator(false);
        // columns
        $this->addPrimaryKey('id', 'Id', 'INTEGER', true, null, null);
        $this->addColumn('vin_number', 'VinNumber', 'VARCHAR', true, 50, null);
        $this->addColumn('lcdv_16', 'Lcdv16', 'VARCHAR', false, 60, null);
        $this->addColumn('lcdv_32', 'Lcdv32', 'VARCHAR', false, 45, null);
        $this->addColumn('reg_number', 'RegNumber', 'VARCHAR', false, 45, null);
        $this->addColumn('first_reg_date', 'FirstRegDate', 'TIMESTAMP', false, null, null);
        $this->addColumn('car_make', 'CarMake', 'VARCHAR', false, 50, null);
        $this->addColumn('model_variant', 'ModelVariant', 'VARCHAR', false, 45, null);
        $this->addColumn('model_finishing', 'ModelFinishing', 'VARCHAR', false, 45, null);
        $this->addColumn('gear_box', 'GearBox', 'VARCHAR', false, 45, null);
        $this->addColumn('outline', 'Outline', 'VARCHAR', false, 45, null);
        $this->addColumn('car_genre', 'CarGenre', 'VARCHAR', false, 45, null);
        $this->addColumn('dealer_code', 'DealerCode', 'VARCHAR', false, 45, null);
        $this->addColumn('dealer_name', 'DealerName', 'VARCHAR', false, 45, null);
        $this->addColumn('last_known_milage', 'LastKnownMilage', 'VARCHAR', false, 45, null);
        $this->addColumn('sysame_updated_at', 'SysameUpdatedAt', 'TIMESTAMP', false, null, null);
        $this->addColumn('created_at', 'CreatedAt', 'TIMESTAMP', false, null, 'CURRENT_TIMESTAMP');
        $this->addColumn('updated_at', 'UpdatedAt', 'TIMESTAMP', false, null, null);
        $this->addColumn('deleted_at', 'DeletedAt', 'TIMESTAMP', false, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('UserCar', 'UserCar', RelationMap::ONE_TO_MANY, array('vin_number' => 'id_car', ), null, null, 'UserCars');
    } // buildRelations()

} // CarTableMap
