<?php



/**
 * This class defines the structure of the 'users_cars' table.
 *
 *
 * This class was autogenerated by Propel 1.6.9 on:
 *
 * Tue 03 Sep 2013 04:07:30 PM EEST
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.cron_project.model.map
 */
class UsersCarsTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.cron_project.model.map.UsersCarsTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('users_cars');
        $this->setPhpName('UsersCars');
        $this->setClassname('UsersCars');
        $this->setPackage('lib.cron_project.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('id', 'Id', 'INTEGER', true, 10, null);
        $this->addForeignKey('id_car', 'IdCar', 'VARCHAR', 'car', 'vin_number', true, 50, null);
        $this->addForeignKey('id_user', 'IdUser', 'INTEGER', 'user', 'sysame_id', true, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('User', 'User', RelationMap::MANY_TO_ONE, array('id_user' => 'sysame_id', ), null, null);
        $this->addRelation('Car', 'Car', RelationMap::MANY_TO_ONE, array('id_car' => 'vin_number', ), null, null);
    } // buildRelations()

} // UsersCarsTableMap
