<?php


/**
 * Base class that represents a row from the 'user' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.9 on:
 *
 * Tue 03 Sep 2013 04:11:14 PM EEST
 *
 * @package    propel.generator.lib.cron_project.model.om
 */
abstract class BaseUser extends BaseObject implements Persistent
{
    /**
     * Peer class name
     */
    const PEER = 'UserPeer';

    /**
     * The Peer class.
     * Instance provides a convenient way of calling static methods on a class
     * that calling code may not be able to identify.
     * @var        UserPeer
     */
    protected static $peer;

    /**
     * The flag var to prevent infinit loop in deep copy
     * @var       boolean
     */
    protected $startCopy = false;

    /**
     * The value for the id field.
     * @var        int
     */
    protected $id;

    /**
     * The value for the sysame_id field.
     * @var        int
     */
    protected $sysame_id;

    /**
     * The value for the forename field.
     * @var        string
     */
    protected $forename;

    /**
     * The value for the surname field.
     * @var        string
     */
    protected $surname;

    /**
     * The value for the street_name field.
     * @var        string
     */
    protected $street_name;

    /**
     * The value for the street_number field.
     * @var        string
     */
    protected $street_number;

    /**
     * The value for the postbox field.
     * @var        string
     */
    protected $postbox;

    /**
     * The value for the zip_code field.
     * @var        string
     */
    protected $zip_code;

    /**
     * The value for the city field.
     * @var        string
     */
    protected $city;

    /**
     * The value for the country field.
     * @var        string
     */
    protected $country;

    /**
     * The value for the email field.
     * @var        string
     */
    protected $email;

    /**
     * The value for the phone_home field.
     * @var        string
     */
    protected $phone_home;

    /**
     * The value for the phone_mobile field.
     * @var        string
     */
    protected $phone_mobile;

    /**
     * The value for the phone_work field.
     * @var        string
     */
    protected $phone_work;

    /**
     * The value for the permission field.
     * Note: this column has a database default value of: 0
     * @var        int
     */
    protected $permission;

    /**
     * The value for the permission_email field.
     * Note: this column has a database default value of: 0
     * @var        int
     */
    protected $permission_email;

    /**
     * The value for the permission_sms field.
     * Note: this column has a database default value of: 0
     * @var        int
     */
    protected $permission_sms;

    /**
     * The value for the date_of_birth field.
     * @var        string
     */
    protected $date_of_birth;

    /**
     * The value for the customer_type field.
     * @var        string
     */
    protected $customer_type;

    /**
     * The value for the sysame_updated_at field.
     * @var        string
     */
    protected $sysame_updated_at;

    /**
     * The value for the created_at field.
     * @var        string
     */
    protected $created_at;

    /**
     * The value for the updated_at field.
     * @var        string
     */
    protected $updated_at;

    /**
     * The value for the deleted_at field.
     * @var        string
     */
    protected $deleted_at;

    /**
     * @var        PropelObjectCollection|UserCar[] Collection to store aggregation of UserCar objects.
     */
    protected $collUserCars;
    protected $collUserCarsPartial;

    /**
     * Flag to prevent endless save loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInSave = false;

    /**
     * Flag to prevent endless validation loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInValidation = false;

    /**
     * Flag to prevent endless clearAllReferences($deep=true) loop, if this object is referenced
     * @var        boolean
     */
    protected $alreadyInClearAllReferencesDeep = false;

    /**
     * An array of objects scheduled for deletion.
     * @var		PropelObjectCollection
     */
    protected $userCarsScheduledForDeletion = null;

    /**
     * Applies default values to this object.
     * This method should be called from the object's constructor (or
     * equivalent initialization method).
     * @see        __construct()
     */
    public function applyDefaultValues()
    {
        $this->permission = 0;
        $this->permission_email = 0;
        $this->permission_sms = 0;
    }

    /**
     * Initializes internal state of BaseUser object.
     * @see        applyDefaults()
     */
    public function __construct()
    {
        parent::__construct();
        $this->applyDefaultValues();
    }

    /**
     * Get the [id] column value.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get the [sysame_id] column value.
     *
     * @return int
     */
    public function getSysameId()
    {
        return $this->sysame_id;
    }

    /**
     * Get the [forename] column value.
     *
     * @return string
     */
    public function getForename()
    {
        return $this->forename;
    }

    /**
     * Get the [surname] column value.
     *
     * @return string
     */
    public function getSurname()
    {
        return $this->surname;
    }

    /**
     * Get the [street_name] column value.
     *
     * @return string
     */
    public function getStreetName()
    {
        return $this->street_name;
    }

    /**
     * Get the [street_number] column value.
     *
     * @return string
     */
    public function getStreetNumber()
    {
        return $this->street_number;
    }

    /**
     * Get the [postbox] column value.
     *
     * @return string
     */
    public function getPostbox()
    {
        return $this->postbox;
    }

    /**
     * Get the [zip_code] column value.
     *
     * @return string
     */
    public function getZipCode()
    {
        return $this->zip_code;
    }

    /**
     * Get the [city] column value.
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Get the [country] column value.
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Get the [email] column value.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Get the [phone_home] column value.
     *
     * @return string
     */
    public function getPhoneHome()
    {
        return $this->phone_home;
    }

    /**
     * Get the [phone_mobile] column value.
     *
     * @return string
     */
    public function getPhoneMobile()
    {
        return $this->phone_mobile;
    }

    /**
     * Get the [phone_work] column value.
     *
     * @return string
     */
    public function getPhoneWork()
    {
        return $this->phone_work;
    }

    /**
     * Get the [permission] column value.
     *
     * @return int
     */
    public function getPermission()
    {
        return $this->permission;
    }

    /**
     * Get the [permission_email] column value.
     *
     * @return int
     */
    public function getPermissionEmail()
    {
        return $this->permission_email;
    }

    /**
     * Get the [permission_sms] column value.
     *
     * @return int
     */
    public function getPermissionSms()
    {
        return $this->permission_sms;
    }

    /**
     * Get the [optionally formatted] temporal [date_of_birth] column value.
     *
     *
     * @param string $format The date/time format string (either date()-style or strftime()-style).
     *				 If format is null, then the raw DateTime object will be returned.
     * @return mixed Formatted date/time value as string or DateTime object (if format is null), null if column is null, and 0 if column value is 0000-00-00 00:00:00
     * @throws PropelException - if unable to parse/validate the date/time value.
     */
    public function getDateOfBirth($format = 'Y-m-d H:i:s')
    {
        if ($this->date_of_birth === null) {
            return null;
        }

        if ($this->date_of_birth === '0000-00-00 00:00:00') {
            // while technically this is not a default value of null,
            // this seems to be closest in meaning.
            return null;
        }

        try {
            $dt = new DateTime($this->date_of_birth);
        } catch (Exception $x) {
            throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date_of_birth, true), $x);
        }

        if ($format === null) {
            // Because propel.useDateTimeClass is true, we return a DateTime object.
            return $dt;
        }

        if (strpos($format, '%') !== false) {
            return strftime($format, $dt->format('U'));
        }

        return $dt->format($format);

    }

    /**
     * Get the [customer_type] column value.
     *
     * @return string
     */
    public function getCustomerType()
    {
        return $this->customer_type;
    }

    /**
     * Get the [optionally formatted] temporal [sysame_updated_at] column value.
     *
     *
     * @param string $format The date/time format string (either date()-style or strftime()-style).
     *				 If format is null, then the raw DateTime object will be returned.
     * @return mixed Formatted date/time value as string or DateTime object (if format is null), null if column is null, and 0 if column value is 0000-00-00 00:00:00
     * @throws PropelException - if unable to parse/validate the date/time value.
     */
    public function getSysameUpdatedAt($format = 'Y-m-d H:i:s')
    {
        if ($this->sysame_updated_at === null) {
            return null;
        }

        if ($this->sysame_updated_at === '0000-00-00 00:00:00') {
            // while technically this is not a default value of null,
            // this seems to be closest in meaning.
            return null;
        }

        try {
            $dt = new DateTime($this->sysame_updated_at);
        } catch (Exception $x) {
            throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->sysame_updated_at, true), $x);
        }

        if ($format === null) {
            // Because propel.useDateTimeClass is true, we return a DateTime object.
            return $dt;
        }

        if (strpos($format, '%') !== false) {
            return strftime($format, $dt->format('U'));
        }

        return $dt->format($format);

    }

    /**
     * Get the [optionally formatted] temporal [created_at] column value.
     *
     *
     * @param string $format The date/time format string (either date()-style or strftime()-style).
     *				 If format is null, then the raw DateTime object will be returned.
     * @return mixed Formatted date/time value as string or DateTime object (if format is null), null if column is null, and 0 if column value is 0000-00-00 00:00:00
     * @throws PropelException - if unable to parse/validate the date/time value.
     */
    public function getCreatedAt($format = 'Y-m-d H:i:s')
    {
        if ($this->created_at === null) {
            return null;
        }

        if ($this->created_at === '0000-00-00 00:00:00') {
            // while technically this is not a default value of null,
            // this seems to be closest in meaning.
            return null;
        }

        try {
            $dt = new DateTime($this->created_at);
        } catch (Exception $x) {
            throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
        }

        if ($format === null) {
            // Because propel.useDateTimeClass is true, we return a DateTime object.
            return $dt;
        }

        if (strpos($format, '%') !== false) {
            return strftime($format, $dt->format('U'));
        }

        return $dt->format($format);

    }

    /**
     * Get the [optionally formatted] temporal [updated_at] column value.
     *
     *
     * @param string $format The date/time format string (either date()-style or strftime()-style).
     *				 If format is null, then the raw DateTime object will be returned.
     * @return mixed Formatted date/time value as string or DateTime object (if format is null), null if column is null, and 0 if column value is 0000-00-00 00:00:00
     * @throws PropelException - if unable to parse/validate the date/time value.
     */
    public function getUpdatedAt($format = 'Y-m-d H:i:s')
    {
        if ($this->updated_at === null) {
            return null;
        }

        if ($this->updated_at === '0000-00-00 00:00:00') {
            // while technically this is not a default value of null,
            // this seems to be closest in meaning.
            return null;
        }

        try {
            $dt = new DateTime($this->updated_at);
        } catch (Exception $x) {
            throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
        }

        if ($format === null) {
            // Because propel.useDateTimeClass is true, we return a DateTime object.
            return $dt;
        }

        if (strpos($format, '%') !== false) {
            return strftime($format, $dt->format('U'));
        }

        return $dt->format($format);

    }

    /**
     * Get the [deleted_at] column value.
     *
     * @return string
     */
    public function getDeletedAt()
    {
        return $this->deleted_at;
    }

    /**
     * Set the value of [id] column.
     *
     * @param int $v new value
     * @return User The current object (for fluent API support)
     */
    public function setId($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (int) $v;
        }

        if ($this->id !== $v) {
            $this->id = $v;
            $this->modifiedColumns[] = UserPeer::ID;
        }


        return $this;
    } // setId()

    /**
     * Set the value of [sysame_id] column.
     *
     * @param int $v new value
     * @return User The current object (for fluent API support)
     */
    public function setSysameId($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (int) $v;
        }

        if ($this->sysame_id !== $v) {
            $this->sysame_id = $v;
            $this->modifiedColumns[] = UserPeer::SYSAME_ID;
        }


        return $this;
    } // setSysameId()

    /**
     * Set the value of [forename] column.
     *
     * @param string $v new value
     * @return User The current object (for fluent API support)
     */
    public function setForename($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->forename !== $v) {
            $this->forename = $v;
            $this->modifiedColumns[] = UserPeer::FORENAME;
        }


        return $this;
    } // setForename()

    /**
     * Set the value of [surname] column.
     *
     * @param string $v new value
     * @return User The current object (for fluent API support)
     */
    public function setSurname($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->surname !== $v) {
            $this->surname = $v;
            $this->modifiedColumns[] = UserPeer::SURNAME;
        }


        return $this;
    } // setSurname()

    /**
     * Set the value of [street_name] column.
     *
     * @param string $v new value
     * @return User The current object (for fluent API support)
     */
    public function setStreetName($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->street_name !== $v) {
            $this->street_name = $v;
            $this->modifiedColumns[] = UserPeer::STREET_NAME;
        }


        return $this;
    } // setStreetName()

    /**
     * Set the value of [street_number] column.
     *
     * @param string $v new value
     * @return User The current object (for fluent API support)
     */
    public function setStreetNumber($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->street_number !== $v) {
            $this->street_number = $v;
            $this->modifiedColumns[] = UserPeer::STREET_NUMBER;
        }


        return $this;
    } // setStreetNumber()

    /**
     * Set the value of [postbox] column.
     *
     * @param string $v new value
     * @return User The current object (for fluent API support)
     */
    public function setPostbox($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->postbox !== $v) {
            $this->postbox = $v;
            $this->modifiedColumns[] = UserPeer::POSTBOX;
        }


        return $this;
    } // setPostbox()

    /**
     * Set the value of [zip_code] column.
     *
     * @param string $v new value
     * @return User The current object (for fluent API support)
     */
    public function setZipCode($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->zip_code !== $v) {
            $this->zip_code = $v;
            $this->modifiedColumns[] = UserPeer::ZIP_CODE;
        }


        return $this;
    } // setZipCode()

    /**
     * Set the value of [city] column.
     *
     * @param string $v new value
     * @return User The current object (for fluent API support)
     */
    public function setCity($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->city !== $v) {
            $this->city = $v;
            $this->modifiedColumns[] = UserPeer::CITY;
        }


        return $this;
    } // setCity()

    /**
     * Set the value of [country] column.
     *
     * @param string $v new value
     * @return User The current object (for fluent API support)
     */
    public function setCountry($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->country !== $v) {
            $this->country = $v;
            $this->modifiedColumns[] = UserPeer::COUNTRY;
        }


        return $this;
    } // setCountry()

    /**
     * Set the value of [email] column.
     *
     * @param string $v new value
     * @return User The current object (for fluent API support)
     */
    public function setEmail($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->email !== $v) {
            $this->email = $v;
            $this->modifiedColumns[] = UserPeer::EMAIL;
        }


        return $this;
    } // setEmail()

    /**
     * Set the value of [phone_home] column.
     *
     * @param string $v new value
     * @return User The current object (for fluent API support)
     */
    public function setPhoneHome($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->phone_home !== $v) {
            $this->phone_home = $v;
            $this->modifiedColumns[] = UserPeer::PHONE_HOME;
        }


        return $this;
    } // setPhoneHome()

    /**
     * Set the value of [phone_mobile] column.
     *
     * @param string $v new value
     * @return User The current object (for fluent API support)
     */
    public function setPhoneMobile($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->phone_mobile !== $v) {
            $this->phone_mobile = $v;
            $this->modifiedColumns[] = UserPeer::PHONE_MOBILE;
        }


        return $this;
    } // setPhoneMobile()

    /**
     * Set the value of [phone_work] column.
     *
     * @param string $v new value
     * @return User The current object (for fluent API support)
     */
    public function setPhoneWork($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->phone_work !== $v) {
            $this->phone_work = $v;
            $this->modifiedColumns[] = UserPeer::PHONE_WORK;
        }


        return $this;
    } // setPhoneWork()

    /**
     * Set the value of [permission] column.
     *
     * @param int $v new value
     * @return User The current object (for fluent API support)
     */
    public function setPermission($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (int) $v;
        }

        if ($this->permission !== $v) {
            $this->permission = $v;
            $this->modifiedColumns[] = UserPeer::PERMISSION;
        }


        return $this;
    } // setPermission()

    /**
     * Set the value of [permission_email] column.
     *
     * @param int $v new value
     * @return User The current object (for fluent API support)
     */
    public function setPermissionEmail($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (int) $v;
        }

        if ($this->permission_email !== $v) {
            $this->permission_email = $v;
            $this->modifiedColumns[] = UserPeer::PERMISSION_EMAIL;
        }


        return $this;
    } // setPermissionEmail()

    /**
     * Set the value of [permission_sms] column.
     *
     * @param int $v new value
     * @return User The current object (for fluent API support)
     */
    public function setPermissionSms($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (int) $v;
        }

        if ($this->permission_sms !== $v) {
            $this->permission_sms = $v;
            $this->modifiedColumns[] = UserPeer::PERMISSION_SMS;
        }


        return $this;
    } // setPermissionSms()

    /**
     * Sets the value of [date_of_birth] column to a normalized version of the date/time value specified.
     *
     * @param mixed $v string, integer (timestamp), or DateTime value.
     *               Empty strings are treated as null.
     * @return User The current object (for fluent API support)
     */
    public function setDateOfBirth($v)
    {
        $dt = PropelDateTime::newInstance($v, null, 'DateTime');
        if ($this->date_of_birth !== null || $dt !== null) {
            $currentDateAsString = ($this->date_of_birth !== null && $tmpDt = new DateTime($this->date_of_birth)) ? $tmpDt->format('Y-m-d H:i:s') : null;
            $newDateAsString = $dt ? $dt->format('Y-m-d H:i:s') : null;
            if ($currentDateAsString !== $newDateAsString) {
                $this->date_of_birth = $newDateAsString;
                $this->modifiedColumns[] = UserPeer::DATE_OF_BIRTH;
            }
        } // if either are not null


        return $this;
    } // setDateOfBirth()

    /**
     * Set the value of [customer_type] column.
     *
     * @param string $v new value
     * @return User The current object (for fluent API support)
     */
    public function setCustomerType($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->customer_type !== $v) {
            $this->customer_type = $v;
            $this->modifiedColumns[] = UserPeer::CUSTOMER_TYPE;
        }


        return $this;
    } // setCustomerType()

    /**
     * Sets the value of [sysame_updated_at] column to a normalized version of the date/time value specified.
     *
     * @param mixed $v string, integer (timestamp), or DateTime value.
     *               Empty strings are treated as null.
     * @return User The current object (for fluent API support)
     */
    public function setSysameUpdatedAt($v)
    {
        $dt = PropelDateTime::newInstance($v, null, 'DateTime');
        if ($this->sysame_updated_at !== null || $dt !== null) {
            $currentDateAsString = ($this->sysame_updated_at !== null && $tmpDt = new DateTime($this->sysame_updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
            $newDateAsString = $dt ? $dt->format('Y-m-d H:i:s') : null;
            if ($currentDateAsString !== $newDateAsString) {
                $this->sysame_updated_at = $newDateAsString;
                $this->modifiedColumns[] = UserPeer::SYSAME_UPDATED_AT;
            }
        } // if either are not null


        return $this;
    } // setSysameUpdatedAt()

    /**
     * Sets the value of [created_at] column to a normalized version of the date/time value specified.
     *
     * @param mixed $v string, integer (timestamp), or DateTime value.
     *               Empty strings are treated as null.
     * @return User The current object (for fluent API support)
     */
    public function setCreatedAt($v)
    {
        $dt = PropelDateTime::newInstance($v, null, 'DateTime');
        if ($this->created_at !== null || $dt !== null) {
            $currentDateAsString = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
            $newDateAsString = $dt ? $dt->format('Y-m-d H:i:s') : null;
            if ($currentDateAsString !== $newDateAsString) {
                $this->created_at = $newDateAsString;
                $this->modifiedColumns[] = UserPeer::CREATED_AT;
            }
        } // if either are not null


        return $this;
    } // setCreatedAt()

    /**
     * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
     *
     * @param mixed $v string, integer (timestamp), or DateTime value.
     *               Empty strings are treated as null.
     * @return User The current object (for fluent API support)
     */
    public function setUpdatedAt($v)
    {
        $dt = PropelDateTime::newInstance($v, null, 'DateTime');
        if ($this->updated_at !== null || $dt !== null) {
            $currentDateAsString = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
            $newDateAsString = $dt ? $dt->format('Y-m-d H:i:s') : null;
            if ($currentDateAsString !== $newDateAsString) {
                $this->updated_at = $newDateAsString;
                $this->modifiedColumns[] = UserPeer::UPDATED_AT;
            }
        } // if either are not null


        return $this;
    } // setUpdatedAt()

    /**
     * Set the value of [deleted_at] column.
     *
     * @param string $v new value
     * @return User The current object (for fluent API support)
     */
    public function setDeletedAt($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->deleted_at !== $v) {
            $this->deleted_at = $v;
            $this->modifiedColumns[] = UserPeer::DELETED_AT;
        }


        return $this;
    } // setDeletedAt()

    /**
     * Indicates whether the columns in this object are only set to default values.
     *
     * This method can be used in conjunction with isModified() to indicate whether an object is both
     * modified _and_ has some values set which are non-default.
     *
     * @return boolean Whether the columns in this object are only been set with default values.
     */
    public function hasOnlyDefaultValues()
    {
            if ($this->permission !== 0) {
                return false;
            }

            if ($this->permission_email !== 0) {
                return false;
            }

            if ($this->permission_sms !== 0) {
                return false;
            }

        // otherwise, everything was equal, so return true
        return true;
    } // hasOnlyDefaultValues()

    /**
     * Hydrates (populates) the object variables with values from the database resultset.
     *
     * An offset (0-based "start column") is specified so that objects can be hydrated
     * with a subset of the columns in the resultset rows.  This is needed, for example,
     * for results of JOIN queries where the resultset row includes columns from two or
     * more tables.
     *
     * @param array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
     * @param int $startcol 0-based offset column which indicates which restultset column to start with.
     * @param boolean $rehydrate Whether this object is being re-hydrated from the database.
     * @return int             next starting column
     * @throws PropelException - Any caught Exception will be rewrapped as a PropelException.
     */
    public function hydrate($row, $startcol = 0, $rehydrate = false)
    {
        try {

            $this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
            $this->sysame_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
            $this->forename = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
            $this->surname = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
            $this->street_name = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
            $this->street_number = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
            $this->postbox = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
            $this->zip_code = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
            $this->city = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
            $this->country = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
            $this->email = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
            $this->phone_home = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
            $this->phone_mobile = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
            $this->phone_work = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
            $this->permission = ($row[$startcol + 14] !== null) ? (int) $row[$startcol + 14] : null;
            $this->permission_email = ($row[$startcol + 15] !== null) ? (int) $row[$startcol + 15] : null;
            $this->permission_sms = ($row[$startcol + 16] !== null) ? (int) $row[$startcol + 16] : null;
            $this->date_of_birth = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
            $this->customer_type = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
            $this->sysame_updated_at = ($row[$startcol + 19] !== null) ? (string) $row[$startcol + 19] : null;
            $this->created_at = ($row[$startcol + 20] !== null) ? (string) $row[$startcol + 20] : null;
            $this->updated_at = ($row[$startcol + 21] !== null) ? (string) $row[$startcol + 21] : null;
            $this->deleted_at = ($row[$startcol + 22] !== null) ? (string) $row[$startcol + 22] : null;
            $this->resetModified();

            $this->setNew(false);

            if ($rehydrate) {
                $this->ensureConsistency();
            }
            $this->postHydrate($row, $startcol, $rehydrate);
            return $startcol + 23; // 23 = UserPeer::NUM_HYDRATE_COLUMNS.

        } catch (Exception $e) {
            throw new PropelException("Error populating User object", $e);
        }
    }

    /**
     * Checks and repairs the internal consistency of the object.
     *
     * This method is executed after an already-instantiated object is re-hydrated
     * from the database.  It exists to check any foreign keys to make sure that
     * the objects related to the current object are correct based on foreign key.
     *
     * You can override this method in the stub class, but you should always invoke
     * the base method from the overridden method (i.e. parent::ensureConsistency()),
     * in case your model changes.
     *
     * @throws PropelException
     */
    public function ensureConsistency()
    {

    } // ensureConsistency

    /**
     * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
     *
     * This will only work if the object has been saved and has a valid primary key set.
     *
     * @param boolean $deep (optional) Whether to also de-associated any related objects.
     * @param PropelPDO $con (optional) The PropelPDO connection to use.
     * @return void
     * @throws PropelException - if this object is deleted, unsaved or doesn't have pk match in db
     */
    public function reload($deep = false, PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("Cannot reload a deleted object.");
        }

        if ($this->isNew()) {
            throw new PropelException("Cannot reload an unsaved object.");
        }

        if ($con === null) {
            $con = Propel::getConnection(UserPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        // We don't need to alter the object instance pool; we're just modifying this instance
        // already in the pool.

        $stmt = UserPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
        $row = $stmt->fetch(PDO::FETCH_NUM);
        $stmt->closeCursor();
        if (!$row) {
            throw new PropelException('Cannot find matching row in the database to reload object values.');
        }
        $this->hydrate($row, 0, true); // rehydrate

        if ($deep) {  // also de-associate any related objects?

            $this->collUserCars = null;

        } // if (deep)
    }

    /**
     * Removes this object from datastore and sets delete attribute.
     *
     * @param PropelPDO $con
     * @return void
     * @throws PropelException
     * @throws Exception
     * @see        BaseObject::setDeleted()
     * @see        BaseObject::isDeleted()
     */
    public function delete(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("This object has already been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(UserPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        try {
            $deleteQuery = UserQuery::create()
                ->filterByPrimaryKey($this->getPrimaryKey());
            $ret = $this->preDelete($con);
            if ($ret) {
                $deleteQuery->delete($con);
                $this->postDelete($con);
                $con->commit();
                $this->setDeleted(true);
            } else {
                $con->commit();
            }
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Persists this object to the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All modified related objects will also be persisted in the doSave()
     * method.  This method wraps all precipitate database operations in a
     * single transaction.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @throws Exception
     * @see        doSave()
     */
    public function save(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("You cannot save an object that has been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(UserPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        $isInsert = $this->isNew();
        try {
            $ret = $this->preSave($con);
            if ($isInsert) {
                $ret = $ret && $this->preInsert($con);
            } else {
                $ret = $ret && $this->preUpdate($con);
            }
            if ($ret) {
                $affectedRows = $this->doSave($con);
                if ($isInsert) {
                    $this->postInsert($con);
                } else {
                    $this->postUpdate($con);
                }
                $this->postSave($con);
                UserPeer::addInstanceToPool($this);
            } else {
                $affectedRows = 0;
            }
            $con->commit();

            return $affectedRows;
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs the work of inserting or updating the row in the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All related objects are also updated in this method.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @see        save()
     */
    protected function doSave(PropelPDO $con)
    {
        $affectedRows = 0; // initialize var to track total num of affected rows
        if (!$this->alreadyInSave) {
            $this->alreadyInSave = true;

            if ($this->isNew() || $this->isModified()) {
                // persist changes
                if ($this->isNew()) {
                    $this->doInsert($con);
                } else {
                    $this->doUpdate($con);
                }
                $affectedRows += 1;
                $this->resetModified();
            }

            if ($this->userCarsScheduledForDeletion !== null) {
                if (!$this->userCarsScheduledForDeletion->isEmpty()) {
                    UserCarQuery::create()
                        ->filterByPrimaryKeys($this->userCarsScheduledForDeletion->getPrimaryKeys(false))
                        ->delete($con);
                    $this->userCarsScheduledForDeletion = null;
                }
            }

            if ($this->collUserCars !== null) {
                foreach ($this->collUserCars as $referrerFK) {
                    if (!$referrerFK->isDeleted() && ($referrerFK->isNew() || $referrerFK->isModified())) {
                        $affectedRows += $referrerFK->save($con);
                    }
                }
            }

            $this->alreadyInSave = false;

        }

        return $affectedRows;
    } // doSave()

    /**
     * Insert the row in the database.
     *
     * @param PropelPDO $con
     *
     * @throws PropelException
     * @see        doSave()
     */
    protected function doInsert(PropelPDO $con)
    {
        $modifiedColumns = array();
        $index = 0;

        $this->modifiedColumns[] = UserPeer::ID;
        if (null !== $this->id) {
            throw new PropelException('Cannot insert a value for auto-increment primary key (' . UserPeer::ID . ')');
        }

         // check the columns in natural order for more readable SQL queries
        if ($this->isColumnModified(UserPeer::ID)) {
            $modifiedColumns[':p' . $index++]  = '`id`';
        }
        if ($this->isColumnModified(UserPeer::SYSAME_ID)) {
            $modifiedColumns[':p' . $index++]  = '`sysame_id`';
        }
        if ($this->isColumnModified(UserPeer::FORENAME)) {
            $modifiedColumns[':p' . $index++]  = '`forename`';
        }
        if ($this->isColumnModified(UserPeer::SURNAME)) {
            $modifiedColumns[':p' . $index++]  = '`surname`';
        }
        if ($this->isColumnModified(UserPeer::STREET_NAME)) {
            $modifiedColumns[':p' . $index++]  = '`street_name`';
        }
        if ($this->isColumnModified(UserPeer::STREET_NUMBER)) {
            $modifiedColumns[':p' . $index++]  = '`street_number`';
        }
        if ($this->isColumnModified(UserPeer::POSTBOX)) {
            $modifiedColumns[':p' . $index++]  = '`postbox`';
        }
        if ($this->isColumnModified(UserPeer::ZIP_CODE)) {
            $modifiedColumns[':p' . $index++]  = '`zip_code`';
        }
        if ($this->isColumnModified(UserPeer::CITY)) {
            $modifiedColumns[':p' . $index++]  = '`city`';
        }
        if ($this->isColumnModified(UserPeer::COUNTRY)) {
            $modifiedColumns[':p' . $index++]  = '`country`';
        }
        if ($this->isColumnModified(UserPeer::EMAIL)) {
            $modifiedColumns[':p' . $index++]  = '`email`';
        }
        if ($this->isColumnModified(UserPeer::PHONE_HOME)) {
            $modifiedColumns[':p' . $index++]  = '`phone_home`';
        }
        if ($this->isColumnModified(UserPeer::PHONE_MOBILE)) {
            $modifiedColumns[':p' . $index++]  = '`phone_mobile`';
        }
        if ($this->isColumnModified(UserPeer::PHONE_WORK)) {
            $modifiedColumns[':p' . $index++]  = '`phone_work`';
        }
        if ($this->isColumnModified(UserPeer::PERMISSION)) {
            $modifiedColumns[':p' . $index++]  = '`permission`';
        }
        if ($this->isColumnModified(UserPeer::PERMISSION_EMAIL)) {
            $modifiedColumns[':p' . $index++]  = '`permission_email`';
        }
        if ($this->isColumnModified(UserPeer::PERMISSION_SMS)) {
            $modifiedColumns[':p' . $index++]  = '`permission_sms`';
        }
        if ($this->isColumnModified(UserPeer::DATE_OF_BIRTH)) {
            $modifiedColumns[':p' . $index++]  = '`date_of_birth`';
        }
        if ($this->isColumnModified(UserPeer::CUSTOMER_TYPE)) {
            $modifiedColumns[':p' . $index++]  = '`customer_type`';
        }
        if ($this->isColumnModified(UserPeer::SYSAME_UPDATED_AT)) {
            $modifiedColumns[':p' . $index++]  = '`sysame_updated_at`';
        }
        if ($this->isColumnModified(UserPeer::CREATED_AT)) {
            $modifiedColumns[':p' . $index++]  = '`created_at`';
        }
        if ($this->isColumnModified(UserPeer::UPDATED_AT)) {
            $modifiedColumns[':p' . $index++]  = '`updated_at`';
        }
        if ($this->isColumnModified(UserPeer::DELETED_AT)) {
            $modifiedColumns[':p' . $index++]  = '`deleted_at`';
        }

        $sql = sprintf(
            'INSERT INTO `user` (%s) VALUES (%s)',
            implode(', ', $modifiedColumns),
            implode(', ', array_keys($modifiedColumns))
        );

        try {
            $stmt = $con->prepare($sql);
            foreach ($modifiedColumns as $identifier => $columnName) {
                switch ($columnName) {
                    case '`id`':
                        $stmt->bindValue($identifier, $this->id, PDO::PARAM_INT);
                        break;
                    case '`sysame_id`':
                        $stmt->bindValue($identifier, $this->sysame_id, PDO::PARAM_INT);
                        break;
                    case '`forename`':
                        $stmt->bindValue($identifier, $this->forename, PDO::PARAM_STR);
                        break;
                    case '`surname`':
                        $stmt->bindValue($identifier, $this->surname, PDO::PARAM_STR);
                        break;
                    case '`street_name`':
                        $stmt->bindValue($identifier, $this->street_name, PDO::PARAM_STR);
                        break;
                    case '`street_number`':
                        $stmt->bindValue($identifier, $this->street_number, PDO::PARAM_STR);
                        break;
                    case '`postbox`':
                        $stmt->bindValue($identifier, $this->postbox, PDO::PARAM_STR);
                        break;
                    case '`zip_code`':
                        $stmt->bindValue($identifier, $this->zip_code, PDO::PARAM_STR);
                        break;
                    case '`city`':
                        $stmt->bindValue($identifier, $this->city, PDO::PARAM_STR);
                        break;
                    case '`country`':
                        $stmt->bindValue($identifier, $this->country, PDO::PARAM_STR);
                        break;
                    case '`email`':
                        $stmt->bindValue($identifier, $this->email, PDO::PARAM_STR);
                        break;
                    case '`phone_home`':
                        $stmt->bindValue($identifier, $this->phone_home, PDO::PARAM_STR);
                        break;
                    case '`phone_mobile`':
                        $stmt->bindValue($identifier, $this->phone_mobile, PDO::PARAM_STR);
                        break;
                    case '`phone_work`':
                        $stmt->bindValue($identifier, $this->phone_work, PDO::PARAM_STR);
                        break;
                    case '`permission`':
                        $stmt->bindValue($identifier, $this->permission, PDO::PARAM_INT);
                        break;
                    case '`permission_email`':
                        $stmt->bindValue($identifier, $this->permission_email, PDO::PARAM_INT);
                        break;
                    case '`permission_sms`':
                        $stmt->bindValue($identifier, $this->permission_sms, PDO::PARAM_INT);
                        break;
                    case '`date_of_birth`':
                        $stmt->bindValue($identifier, $this->date_of_birth, PDO::PARAM_STR);
                        break;
                    case '`customer_type`':
                        $stmt->bindValue($identifier, $this->customer_type, PDO::PARAM_STR);
                        break;
                    case '`sysame_updated_at`':
                        $stmt->bindValue($identifier, $this->sysame_updated_at, PDO::PARAM_STR);
                        break;
                    case '`created_at`':
                        $stmt->bindValue($identifier, $this->created_at, PDO::PARAM_STR);
                        break;
                    case '`updated_at`':
                        $stmt->bindValue($identifier, $this->updated_at, PDO::PARAM_STR);
                        break;
                    case '`deleted_at`':
                        $stmt->bindValue($identifier, $this->deleted_at, PDO::PARAM_STR);
                        break;
                }
            }
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
        }

        try {
            $pk = $con->lastInsertId();
        } catch (Exception $e) {
            throw new PropelException('Unable to get autoincrement id.', $e);
        }
        $this->setId($pk);

        $this->setNew(false);
    }

    /**
     * Update the row in the database.
     *
     * @param PropelPDO $con
     *
     * @see        doSave()
     */
    protected function doUpdate(PropelPDO $con)
    {
        $selectCriteria = $this->buildPkeyCriteria();
        $valuesCriteria = $this->buildCriteria();
        BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
    }

    /**
     * Array of ValidationFailed objects.
     * @var        array ValidationFailed[]
     */
    protected $validationFailures = array();

    /**
     * Gets any ValidationFailed objects that resulted from last call to validate().
     *
     *
     * @return array ValidationFailed[]
     * @see        validate()
     */
    public function getValidationFailures()
    {
        return $this->validationFailures;
    }

    /**
     * Validates the objects modified field values and all objects related to this table.
     *
     * If $columns is either a column name or an array of column names
     * only those columns are validated.
     *
     * @param mixed $columns Column name or an array of column names.
     * @return boolean Whether all columns pass validation.
     * @see        doValidate()
     * @see        getValidationFailures()
     */
    public function validate($columns = null)
    {
        $res = $this->doValidate($columns);
        if ($res === true) {
            $this->validationFailures = array();

            return true;
        }

        $this->validationFailures = $res;

        return false;
    }

    /**
     * This function performs the validation work for complex object models.
     *
     * In addition to checking the current object, all related objects will
     * also be validated.  If all pass then <code>true</code> is returned; otherwise
     * an aggreagated array of ValidationFailed objects will be returned.
     *
     * @param array $columns Array of column names to validate.
     * @return mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
     */
    protected function doValidate($columns = null)
    {
        if (!$this->alreadyInValidation) {
            $this->alreadyInValidation = true;
            $retval = null;

            $failureMap = array();


            if (($retval = UserPeer::doValidate($this, $columns)) !== true) {
                $failureMap = array_merge($failureMap, $retval);
            }


                if ($this->collUserCars !== null) {
                    foreach ($this->collUserCars as $referrerFK) {
                        if (!$referrerFK->validate($columns)) {
                            $failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
                        }
                    }
                }


            $this->alreadyInValidation = false;
        }

        return (!empty($failureMap) ? $failureMap : true);
    }

    /**
     * Retrieves a field from the object by name passed in as a string.
     *
     * @param string $name name
     * @param string $type The type of fieldname the $name is of:
     *               one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *               BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *               Defaults to BasePeer::TYPE_PHPNAME
     * @return mixed Value of field.
     */
    public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = UserPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
        $field = $this->getByPosition($pos);

        return $field;
    }

    /**
     * Retrieves a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @return mixed Value of field at $pos
     */
    public function getByPosition($pos)
    {
        switch ($pos) {
            case 0:
                return $this->getId();
                break;
            case 1:
                return $this->getSysameId();
                break;
            case 2:
                return $this->getForename();
                break;
            case 3:
                return $this->getSurname();
                break;
            case 4:
                return $this->getStreetName();
                break;
            case 5:
                return $this->getStreetNumber();
                break;
            case 6:
                return $this->getPostbox();
                break;
            case 7:
                return $this->getZipCode();
                break;
            case 8:
                return $this->getCity();
                break;
            case 9:
                return $this->getCountry();
                break;
            case 10:
                return $this->getEmail();
                break;
            case 11:
                return $this->getPhoneHome();
                break;
            case 12:
                return $this->getPhoneMobile();
                break;
            case 13:
                return $this->getPhoneWork();
                break;
            case 14:
                return $this->getPermission();
                break;
            case 15:
                return $this->getPermissionEmail();
                break;
            case 16:
                return $this->getPermissionSms();
                break;
            case 17:
                return $this->getDateOfBirth();
                break;
            case 18:
                return $this->getCustomerType();
                break;
            case 19:
                return $this->getSysameUpdatedAt();
                break;
            case 20:
                return $this->getCreatedAt();
                break;
            case 21:
                return $this->getUpdatedAt();
                break;
            case 22:
                return $this->getDeletedAt();
                break;
            default:
                return null;
                break;
        } // switch()
    }

    /**
     * Exports the object as an array.
     *
     * You can specify the key type of the array by passing one of the class
     * type constants.
     *
     * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                    Defaults to BasePeer::TYPE_PHPNAME.
     * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to true.
     * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
     * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
     *
     * @return array an associative array containing the field names (as keys) and field values
     */
    public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array(), $includeForeignObjects = false)
    {
        if (isset($alreadyDumpedObjects['User'][$this->getPrimaryKey()])) {
            return '*RECURSION*';
        }
        $alreadyDumpedObjects['User'][$this->getPrimaryKey()] = true;
        $keys = UserPeer::getFieldNames($keyType);
        $result = array(
            $keys[0] => $this->getId(),
            $keys[1] => $this->getSysameId(),
            $keys[2] => $this->getForename(),
            $keys[3] => $this->getSurname(),
            $keys[4] => $this->getStreetName(),
            $keys[5] => $this->getStreetNumber(),
            $keys[6] => $this->getPostbox(),
            $keys[7] => $this->getZipCode(),
            $keys[8] => $this->getCity(),
            $keys[9] => $this->getCountry(),
            $keys[10] => $this->getEmail(),
            $keys[11] => $this->getPhoneHome(),
            $keys[12] => $this->getPhoneMobile(),
            $keys[13] => $this->getPhoneWork(),
            $keys[14] => $this->getPermission(),
            $keys[15] => $this->getPermissionEmail(),
            $keys[16] => $this->getPermissionSms(),
            $keys[17] => $this->getDateOfBirth(),
            $keys[18] => $this->getCustomerType(),
            $keys[19] => $this->getSysameUpdatedAt(),
            $keys[20] => $this->getCreatedAt(),
            $keys[21] => $this->getUpdatedAt(),
            $keys[22] => $this->getDeletedAt(),
        );
        if ($includeForeignObjects) {
            if (null !== $this->collUserCars) {
                $result['UserCars'] = $this->collUserCars->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
            }
        }

        return $result;
    }

    /**
     * Sets a field from the object by name passed in as a string.
     *
     * @param string $name peer name
     * @param mixed $value field value
     * @param string $type The type of fieldname the $name is of:
     *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                     Defaults to BasePeer::TYPE_PHPNAME
     * @return void
     */
    public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = UserPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);

        $this->setByPosition($pos, $value);
    }

    /**
     * Sets a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @param mixed $value field value
     * @return void
     */
    public function setByPosition($pos, $value)
    {
        switch ($pos) {
            case 0:
                $this->setId($value);
                break;
            case 1:
                $this->setSysameId($value);
                break;
            case 2:
                $this->setForename($value);
                break;
            case 3:
                $this->setSurname($value);
                break;
            case 4:
                $this->setStreetName($value);
                break;
            case 5:
                $this->setStreetNumber($value);
                break;
            case 6:
                $this->setPostbox($value);
                break;
            case 7:
                $this->setZipCode($value);
                break;
            case 8:
                $this->setCity($value);
                break;
            case 9:
                $this->setCountry($value);
                break;
            case 10:
                $this->setEmail($value);
                break;
            case 11:
                $this->setPhoneHome($value);
                break;
            case 12:
                $this->setPhoneMobile($value);
                break;
            case 13:
                $this->setPhoneWork($value);
                break;
            case 14:
                $this->setPermission($value);
                break;
            case 15:
                $this->setPermissionEmail($value);
                break;
            case 16:
                $this->setPermissionSms($value);
                break;
            case 17:
                $this->setDateOfBirth($value);
                break;
            case 18:
                $this->setCustomerType($value);
                break;
            case 19:
                $this->setSysameUpdatedAt($value);
                break;
            case 20:
                $this->setCreatedAt($value);
                break;
            case 21:
                $this->setUpdatedAt($value);
                break;
            case 22:
                $this->setDeletedAt($value);
                break;
        } // switch()
    }

    /**
     * Populates the object using an array.
     *
     * This is particularly useful when populating an object from one of the
     * request arrays (e.g. $_POST).  This method goes through the column
     * names, checking to see whether a matching key exists in populated
     * array. If so the setByName() method is called for that column.
     *
     * You can specify the key type of the array by additionally passing one
     * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     * The default key type is the column's BasePeer::TYPE_PHPNAME
     *
     * @param array  $arr     An array to populate the object from.
     * @param string $keyType The type of keys the array uses.
     * @return void
     */
    public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
    {
        $keys = UserPeer::getFieldNames($keyType);

        if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
        if (array_key_exists($keys[1], $arr)) $this->setSysameId($arr[$keys[1]]);
        if (array_key_exists($keys[2], $arr)) $this->setForename($arr[$keys[2]]);
        if (array_key_exists($keys[3], $arr)) $this->setSurname($arr[$keys[3]]);
        if (array_key_exists($keys[4], $arr)) $this->setStreetName($arr[$keys[4]]);
        if (array_key_exists($keys[5], $arr)) $this->setStreetNumber($arr[$keys[5]]);
        if (array_key_exists($keys[6], $arr)) $this->setPostbox($arr[$keys[6]]);
        if (array_key_exists($keys[7], $arr)) $this->setZipCode($arr[$keys[7]]);
        if (array_key_exists($keys[8], $arr)) $this->setCity($arr[$keys[8]]);
        if (array_key_exists($keys[9], $arr)) $this->setCountry($arr[$keys[9]]);
        if (array_key_exists($keys[10], $arr)) $this->setEmail($arr[$keys[10]]);
        if (array_key_exists($keys[11], $arr)) $this->setPhoneHome($arr[$keys[11]]);
        if (array_key_exists($keys[12], $arr)) $this->setPhoneMobile($arr[$keys[12]]);
        if (array_key_exists($keys[13], $arr)) $this->setPhoneWork($arr[$keys[13]]);
        if (array_key_exists($keys[14], $arr)) $this->setPermission($arr[$keys[14]]);
        if (array_key_exists($keys[15], $arr)) $this->setPermissionEmail($arr[$keys[15]]);
        if (array_key_exists($keys[16], $arr)) $this->setPermissionSms($arr[$keys[16]]);
        if (array_key_exists($keys[17], $arr)) $this->setDateOfBirth($arr[$keys[17]]);
        if (array_key_exists($keys[18], $arr)) $this->setCustomerType($arr[$keys[18]]);
        if (array_key_exists($keys[19], $arr)) $this->setSysameUpdatedAt($arr[$keys[19]]);
        if (array_key_exists($keys[20], $arr)) $this->setCreatedAt($arr[$keys[20]]);
        if (array_key_exists($keys[21], $arr)) $this->setUpdatedAt($arr[$keys[21]]);
        if (array_key_exists($keys[22], $arr)) $this->setDeletedAt($arr[$keys[22]]);
    }

    /**
     * Build a Criteria object containing the values of all modified columns in this object.
     *
     * @return Criteria The Criteria object containing all modified values.
     */
    public function buildCriteria()
    {
        $criteria = new Criteria(UserPeer::DATABASE_NAME);

        if ($this->isColumnModified(UserPeer::ID)) $criteria->add(UserPeer::ID, $this->id);
        if ($this->isColumnModified(UserPeer::SYSAME_ID)) $criteria->add(UserPeer::SYSAME_ID, $this->sysame_id);
        if ($this->isColumnModified(UserPeer::FORENAME)) $criteria->add(UserPeer::FORENAME, $this->forename);
        if ($this->isColumnModified(UserPeer::SURNAME)) $criteria->add(UserPeer::SURNAME, $this->surname);
        if ($this->isColumnModified(UserPeer::STREET_NAME)) $criteria->add(UserPeer::STREET_NAME, $this->street_name);
        if ($this->isColumnModified(UserPeer::STREET_NUMBER)) $criteria->add(UserPeer::STREET_NUMBER, $this->street_number);
        if ($this->isColumnModified(UserPeer::POSTBOX)) $criteria->add(UserPeer::POSTBOX, $this->postbox);
        if ($this->isColumnModified(UserPeer::ZIP_CODE)) $criteria->add(UserPeer::ZIP_CODE, $this->zip_code);
        if ($this->isColumnModified(UserPeer::CITY)) $criteria->add(UserPeer::CITY, $this->city);
        if ($this->isColumnModified(UserPeer::COUNTRY)) $criteria->add(UserPeer::COUNTRY, $this->country);
        if ($this->isColumnModified(UserPeer::EMAIL)) $criteria->add(UserPeer::EMAIL, $this->email);
        if ($this->isColumnModified(UserPeer::PHONE_HOME)) $criteria->add(UserPeer::PHONE_HOME, $this->phone_home);
        if ($this->isColumnModified(UserPeer::PHONE_MOBILE)) $criteria->add(UserPeer::PHONE_MOBILE, $this->phone_mobile);
        if ($this->isColumnModified(UserPeer::PHONE_WORK)) $criteria->add(UserPeer::PHONE_WORK, $this->phone_work);
        if ($this->isColumnModified(UserPeer::PERMISSION)) $criteria->add(UserPeer::PERMISSION, $this->permission);
        if ($this->isColumnModified(UserPeer::PERMISSION_EMAIL)) $criteria->add(UserPeer::PERMISSION_EMAIL, $this->permission_email);
        if ($this->isColumnModified(UserPeer::PERMISSION_SMS)) $criteria->add(UserPeer::PERMISSION_SMS, $this->permission_sms);
        if ($this->isColumnModified(UserPeer::DATE_OF_BIRTH)) $criteria->add(UserPeer::DATE_OF_BIRTH, $this->date_of_birth);
        if ($this->isColumnModified(UserPeer::CUSTOMER_TYPE)) $criteria->add(UserPeer::CUSTOMER_TYPE, $this->customer_type);
        if ($this->isColumnModified(UserPeer::SYSAME_UPDATED_AT)) $criteria->add(UserPeer::SYSAME_UPDATED_AT, $this->sysame_updated_at);
        if ($this->isColumnModified(UserPeer::CREATED_AT)) $criteria->add(UserPeer::CREATED_AT, $this->created_at);
        if ($this->isColumnModified(UserPeer::UPDATED_AT)) $criteria->add(UserPeer::UPDATED_AT, $this->updated_at);
        if ($this->isColumnModified(UserPeer::DELETED_AT)) $criteria->add(UserPeer::DELETED_AT, $this->deleted_at);

        return $criteria;
    }

    /**
     * Builds a Criteria object containing the primary key for this object.
     *
     * Unlike buildCriteria() this method includes the primary key values regardless
     * of whether or not they have been modified.
     *
     * @return Criteria The Criteria object containing value(s) for primary key(s).
     */
    public function buildPkeyCriteria()
    {
        $criteria = new Criteria(UserPeer::DATABASE_NAME);
        $criteria->add(UserPeer::ID, $this->id);

        return $criteria;
    }

    /**
     * Returns the primary key for this object (row).
     * @return int
     */
    public function getPrimaryKey()
    {
        return $this->getId();
    }

    /**
     * Generic method to set the primary key (id column).
     *
     * @param  int $key Primary key.
     * @return void
     */
    public function setPrimaryKey($key)
    {
        $this->setId($key);
    }

    /**
     * Returns true if the primary key for this object is null.
     * @return boolean
     */
    public function isPrimaryKeyNull()
    {

        return null === $this->getId();
    }

    /**
     * Sets contents of passed object to values from current object.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param object $copyObj An object of User (or compatible) type.
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @param boolean $makeNew Whether to reset autoincrement PKs and make the object new.
     * @throws PropelException
     */
    public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
    {
        $copyObj->setSysameId($this->getSysameId());
        $copyObj->setForename($this->getForename());
        $copyObj->setSurname($this->getSurname());
        $copyObj->setStreetName($this->getStreetName());
        $copyObj->setStreetNumber($this->getStreetNumber());
        $copyObj->setPostbox($this->getPostbox());
        $copyObj->setZipCode($this->getZipCode());
        $copyObj->setCity($this->getCity());
        $copyObj->setCountry($this->getCountry());
        $copyObj->setEmail($this->getEmail());
        $copyObj->setPhoneHome($this->getPhoneHome());
        $copyObj->setPhoneMobile($this->getPhoneMobile());
        $copyObj->setPhoneWork($this->getPhoneWork());
        $copyObj->setPermission($this->getPermission());
        $copyObj->setPermissionEmail($this->getPermissionEmail());
        $copyObj->setPermissionSms($this->getPermissionSms());
        $copyObj->setDateOfBirth($this->getDateOfBirth());
        $copyObj->setCustomerType($this->getCustomerType());
        $copyObj->setSysameUpdatedAt($this->getSysameUpdatedAt());
        $copyObj->setCreatedAt($this->getCreatedAt());
        $copyObj->setUpdatedAt($this->getUpdatedAt());
        $copyObj->setDeletedAt($this->getDeletedAt());

        if ($deepCopy && !$this->startCopy) {
            // important: temporarily setNew(false) because this affects the behavior of
            // the getter/setter methods for fkey referrer objects.
            $copyObj->setNew(false);
            // store object hash to prevent cycle
            $this->startCopy = true;

            foreach ($this->getUserCars() as $relObj) {
                if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
                    $copyObj->addUserCar($relObj->copy($deepCopy));
                }
            }

            //unflag object copy
            $this->startCopy = false;
        } // if ($deepCopy)

        if ($makeNew) {
            $copyObj->setNew(true);
            $copyObj->setId(NULL); // this is a auto-increment column, so set to default value
        }
    }

    /**
     * Makes a copy of this object that will be inserted as a new row in table when saved.
     * It creates a new object filling in the simple attributes, but skipping any primary
     * keys that are defined for the table.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @return User Clone of current object.
     * @throws PropelException
     */
    public function copy($deepCopy = false)
    {
        // we use get_class(), because this might be a subclass
        $clazz = get_class($this);
        $copyObj = new $clazz();
        $this->copyInto($copyObj, $deepCopy);

        return $copyObj;
    }

    /**
     * Returns a peer instance associated with this om.
     *
     * Since Peer classes are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     *
     * @return UserPeer
     */
    public function getPeer()
    {
        if (self::$peer === null) {
            self::$peer = new UserPeer();
        }

        return self::$peer;
    }


    /**
     * Initializes a collection based on the name of a relation.
     * Avoids crafting an 'init[$relationName]s' method name
     * that wouldn't work when StandardEnglishPluralizer is used.
     *
     * @param string $relationName The name of the relation to initialize
     * @return void
     */
    public function initRelation($relationName)
    {
        if ('UserCar' == $relationName) {
            $this->initUserCars();
        }
    }

    /**
     * Clears out the collUserCars collection
     *
     * This does not modify the database; however, it will remove any associated objects, causing
     * them to be refetched by subsequent calls to accessor method.
     *
     * @return User The current object (for fluent API support)
     * @see        addUserCars()
     */
    public function clearUserCars()
    {
        $this->collUserCars = null; // important to set this to null since that means it is uninitialized
        $this->collUserCarsPartial = null;

        return $this;
    }

    /**
     * reset is the collUserCars collection loaded partially
     *
     * @return void
     */
    public function resetPartialUserCars($v = true)
    {
        $this->collUserCarsPartial = $v;
    }

    /**
     * Initializes the collUserCars collection.
     *
     * By default this just sets the collUserCars collection to an empty array (like clearcollUserCars());
     * however, you may wish to override this method in your stub class to provide setting appropriate
     * to your application -- for example, setting the initial array to the values stored in database.
     *
     * @param boolean $overrideExisting If set to true, the method call initializes
     *                                        the collection even if it is not empty
     *
     * @return void
     */
    public function initUserCars($overrideExisting = true)
    {
        if (null !== $this->collUserCars && !$overrideExisting) {
            return;
        }
        $this->collUserCars = new PropelObjectCollection();
        $this->collUserCars->setModel('UserCar');
    }

    /**
     * Gets an array of UserCar objects which contain a foreign key that references this object.
     *
     * If the $criteria is not null, it is used to always fetch the results from the database.
     * Otherwise the results are fetched from the database the first time, then cached.
     * Next time the same method is called without $criteria, the cached collection is returned.
     * If this User is new, it will return
     * an empty collection or the current collection; the criteria is ignored on a new object.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @return PropelObjectCollection|UserCar[] List of UserCar objects
     * @throws PropelException
     */
    public function getUserCars($criteria = null, PropelPDO $con = null)
    {
        $partial = $this->collUserCarsPartial && !$this->isNew();
        if (null === $this->collUserCars || null !== $criteria  || $partial) {
            if ($this->isNew() && null === $this->collUserCars) {
                // return empty collection
                $this->initUserCars();
            } else {
                $collUserCars = UserCarQuery::create(null, $criteria)
                    ->filterByUser($this)
                    ->find($con);
                if (null !== $criteria) {
                    if (false !== $this->collUserCarsPartial && count($collUserCars)) {
                      $this->initUserCars(false);

                      foreach($collUserCars as $obj) {
                        if (false == $this->collUserCars->contains($obj)) {
                          $this->collUserCars->append($obj);
                        }
                      }

                      $this->collUserCarsPartial = true;
                    }

                    $collUserCars->getInternalIterator()->rewind();
                    return $collUserCars;
                }

                if($partial && $this->collUserCars) {
                    foreach($this->collUserCars as $obj) {
                        if($obj->isNew()) {
                            $collUserCars[] = $obj;
                        }
                    }
                }

                $this->collUserCars = $collUserCars;
                $this->collUserCarsPartial = false;
            }
        }

        return $this->collUserCars;
    }

    /**
     * Sets a collection of UserCar objects related by a one-to-many relationship
     * to the current object.
     * It will also schedule objects for deletion based on a diff between old objects (aka persisted)
     * and new objects from the given Propel collection.
     *
     * @param PropelCollection $userCars A Propel collection.
     * @param PropelPDO $con Optional connection object
     * @return User The current object (for fluent API support)
     */
    public function setUserCars(PropelCollection $userCars, PropelPDO $con = null)
    {
        $userCarsToDelete = $this->getUserCars(new Criteria(), $con)->diff($userCars);

        $this->userCarsScheduledForDeletion = unserialize(serialize($userCarsToDelete));

        foreach ($userCarsToDelete as $userCarRemoved) {
            $userCarRemoved->setUser(null);
        }

        $this->collUserCars = null;
        foreach ($userCars as $userCar) {
            $this->addUserCar($userCar);
        }

        $this->collUserCars = $userCars;
        $this->collUserCarsPartial = false;

        return $this;
    }

    /**
     * Returns the number of related UserCar objects.
     *
     * @param Criteria $criteria
     * @param boolean $distinct
     * @param PropelPDO $con
     * @return int             Count of related UserCar objects.
     * @throws PropelException
     */
    public function countUserCars(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
    {
        $partial = $this->collUserCarsPartial && !$this->isNew();
        if (null === $this->collUserCars || null !== $criteria || $partial) {
            if ($this->isNew() && null === $this->collUserCars) {
                return 0;
            }

            if($partial && !$criteria) {
                return count($this->getUserCars());
            }
            $query = UserCarQuery::create(null, $criteria);
            if ($distinct) {
                $query->distinct();
            }

            return $query
                ->filterByUser($this)
                ->count($con);
        }

        return count($this->collUserCars);
    }

    /**
     * Method called to associate a UserCar object to this object
     * through the UserCar foreign key attribute.
     *
     * @param    UserCar $l UserCar
     * @return User The current object (for fluent API support)
     */
    public function addUserCar(UserCar $l)
    {
        if ($this->collUserCars === null) {
            $this->initUserCars();
            $this->collUserCarsPartial = true;
        }
        if (!in_array($l, $this->collUserCars->getArrayCopy(), true)) { // only add it if the **same** object is not already associated
            $this->doAddUserCar($l);
        }

        return $this;
    }

    /**
     * @param	UserCar $userCar The userCar object to add.
     */
    protected function doAddUserCar($userCar)
    {
        $this->collUserCars[]= $userCar;
        $userCar->setUser($this);
    }

    /**
     * @param	UserCar $userCar The userCar object to remove.
     * @return User The current object (for fluent API support)
     */
    public function removeUserCar($userCar)
    {
        if ($this->getUserCars()->contains($userCar)) {
            $this->collUserCars->remove($this->collUserCars->search($userCar));
            if (null === $this->userCarsScheduledForDeletion) {
                $this->userCarsScheduledForDeletion = clone $this->collUserCars;
                $this->userCarsScheduledForDeletion->clear();
            }
            $this->userCarsScheduledForDeletion[]= clone $userCar;
            $userCar->setUser(null);
        }

        return $this;
    }


    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this User is new, it will return
     * an empty collection; or if this User has previously
     * been saved, it will retrieve related UserCars from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in User.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @param string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
     * @return PropelObjectCollection|UserCar[] List of UserCar objects
     */
    public function getUserCarsJoinCar($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $query = UserCarQuery::create(null, $criteria);
        $query->joinWith('Car', $join_behavior);

        return $this->getUserCars($query, $con);
    }

    /**
     * Clears the current object and sets all attributes to their default values
     */
    public function clear()
    {
        $this->id = null;
        $this->sysame_id = null;
        $this->forename = null;
        $this->surname = null;
        $this->street_name = null;
        $this->street_number = null;
        $this->postbox = null;
        $this->zip_code = null;
        $this->city = null;
        $this->country = null;
        $this->email = null;
        $this->phone_home = null;
        $this->phone_mobile = null;
        $this->phone_work = null;
        $this->permission = null;
        $this->permission_email = null;
        $this->permission_sms = null;
        $this->date_of_birth = null;
        $this->customer_type = null;
        $this->sysame_updated_at = null;
        $this->created_at = null;
        $this->updated_at = null;
        $this->deleted_at = null;
        $this->alreadyInSave = false;
        $this->alreadyInValidation = false;
        $this->alreadyInClearAllReferencesDeep = false;
        $this->clearAllReferences();
        $this->applyDefaultValues();
        $this->resetModified();
        $this->setNew(true);
        $this->setDeleted(false);
    }

    /**
     * Resets all references to other model objects or collections of model objects.
     *
     * This method is a user-space workaround for PHP's inability to garbage collect
     * objects with circular references (even in PHP 5.3). This is currently necessary
     * when using Propel in certain daemon or large-volumne/high-memory operations.
     *
     * @param boolean $deep Whether to also clear the references on all referrer objects.
     */
    public function clearAllReferences($deep = false)
    {
        if ($deep && !$this->alreadyInClearAllReferencesDeep) {
            $this->alreadyInClearAllReferencesDeep = true;
            if ($this->collUserCars) {
                foreach ($this->collUserCars as $o) {
                    $o->clearAllReferences($deep);
                }
            }

            $this->alreadyInClearAllReferencesDeep = false;
        } // if ($deep)

        if ($this->collUserCars instanceof PropelCollection) {
            $this->collUserCars->clearIterator();
        }
        $this->collUserCars = null;
    }

    /**
     * return the string representation of this object
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->exportTo(UserPeer::DEFAULT_STRING_FORMAT);
    }

    /**
     * return true is the object is in saving state
     *
     * @return boolean
     */
    public function isAlreadyInSave()
    {
        return $this->alreadyInSave;
    }

}
