<?php


/**
 * Base static class for performing query and update operations on the 'car' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.9 on:
 *
 * Tue 03 Sep 2013 04:11:14 PM EEST
 *
 * @package propel.generator.lib.cron_project.model.om
 */
abstract class BaseCarPeer
{

    /** the default database name for this class */
    const DATABASE_NAME = 'cron_project';

    /** the table name for this class */
    const TABLE_NAME = 'car';

    /** the related Propel class for this table */
    const OM_CLASS = 'Car';

    /** the related TableMap class for this table */
    const TM_CLASS = 'CarTableMap';

    /** The total number of columns. */
    const NUM_COLUMNS = 19;

    /** The number of lazy-loaded columns. */
    const NUM_LAZY_LOAD_COLUMNS = 0;

    /** The number of columns to hydrate (NUM_COLUMNS - NUM_LAZY_LOAD_COLUMNS) */
    const NUM_HYDRATE_COLUMNS = 19;

    /** the column name for the id field */
    const ID = 'car.id';

    /** the column name for the vin_number field */
    const VIN_NUMBER = 'car.vin_number';

    /** the column name for the lcdv_16 field */
    const LCDV_16 = 'car.lcdv_16';

    /** the column name for the lcdv_32 field */
    const LCDV_32 = 'car.lcdv_32';

    /** the column name for the reg_number field */
    const REG_NUMBER = 'car.reg_number';

    /** the column name for the first_reg_date field */
    const FIRST_REG_DATE = 'car.first_reg_date';

    /** the column name for the car_make field */
    const CAR_MAKE = 'car.car_make';

    /** the column name for the model_variant field */
    const MODEL_VARIANT = 'car.model_variant';

    /** the column name for the model_finishing field */
    const MODEL_FINISHING = 'car.model_finishing';

    /** the column name for the gear_box field */
    const GEAR_BOX = 'car.gear_box';

    /** the column name for the outline field */
    const OUTLINE = 'car.outline';

    /** the column name for the car_genre field */
    const CAR_GENRE = 'car.car_genre';

    /** the column name for the dealer_code field */
    const DEALER_CODE = 'car.dealer_code';

    /** the column name for the dealer_name field */
    const DEALER_NAME = 'car.dealer_name';

    /** the column name for the last_known_milage field */
    const LAST_KNOWN_MILAGE = 'car.last_known_milage';

    /** the column name for the sysame_updated_at field */
    const SYSAME_UPDATED_AT = 'car.sysame_updated_at';

    /** the column name for the created_at field */
    const CREATED_AT = 'car.created_at';

    /** the column name for the updated_at field */
    const UPDATED_AT = 'car.updated_at';

    /** the column name for the deleted_at field */
    const DELETED_AT = 'car.deleted_at';

    /** The default string format for model objects of the related table **/
    const DEFAULT_STRING_FORMAT = 'YAML';

    /**
     * An identiy map to hold any loaded instances of Car objects.
     * This must be public so that other peer classes can access this when hydrating from JOIN
     * queries.
     * @var        array Car[]
     */
    public static $instances = array();


    /**
     * holds an array of fieldnames
     *
     * first dimension keys are the type constants
     * e.g. CarPeer::$fieldNames[CarPeer::TYPE_PHPNAME][0] = 'Id'
     */
    protected static $fieldNames = array (
        BasePeer::TYPE_PHPNAME => array ('Id', 'VinNumber', 'Lcdv16', 'Lcdv32', 'RegNumber', 'FirstRegDate', 'CarMake', 'ModelVariant', 'ModelFinishing', 'GearBox', 'Outline', 'CarGenre', 'DealerCode', 'DealerName', 'LastKnownMilage', 'SysameUpdatedAt', 'CreatedAt', 'UpdatedAt', 'DeletedAt', ),
        BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'vinNumber', 'lcdv16', 'lcdv32', 'regNumber', 'firstRegDate', 'carMake', 'modelVariant', 'modelFinishing', 'gearBox', 'outline', 'carGenre', 'dealerCode', 'dealerName', 'lastKnownMilage', 'sysameUpdatedAt', 'createdAt', 'updatedAt', 'deletedAt', ),
        BasePeer::TYPE_COLNAME => array (CarPeer::ID, CarPeer::VIN_NUMBER, CarPeer::LCDV_16, CarPeer::LCDV_32, CarPeer::REG_NUMBER, CarPeer::FIRST_REG_DATE, CarPeer::CAR_MAKE, CarPeer::MODEL_VARIANT, CarPeer::MODEL_FINISHING, CarPeer::GEAR_BOX, CarPeer::OUTLINE, CarPeer::CAR_GENRE, CarPeer::DEALER_CODE, CarPeer::DEALER_NAME, CarPeer::LAST_KNOWN_MILAGE, CarPeer::SYSAME_UPDATED_AT, CarPeer::CREATED_AT, CarPeer::UPDATED_AT, CarPeer::DELETED_AT, ),
        BasePeer::TYPE_RAW_COLNAME => array ('ID', 'VIN_NUMBER', 'LCDV_16', 'LCDV_32', 'REG_NUMBER', 'FIRST_REG_DATE', 'CAR_MAKE', 'MODEL_VARIANT', 'MODEL_FINISHING', 'GEAR_BOX', 'OUTLINE', 'CAR_GENRE', 'DEALER_CODE', 'DEALER_NAME', 'LAST_KNOWN_MILAGE', 'SYSAME_UPDATED_AT', 'CREATED_AT', 'UPDATED_AT', 'DELETED_AT', ),
        BasePeer::TYPE_FIELDNAME => array ('id', 'vin_number', 'lcdv_16', 'lcdv_32', 'reg_number', 'first_reg_date', 'car_make', 'model_variant', 'model_finishing', 'gear_box', 'outline', 'car_genre', 'dealer_code', 'dealer_name', 'last_known_milage', 'sysame_updated_at', 'created_at', 'updated_at', 'deleted_at', ),
        BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, )
    );

    /**
     * holds an array of keys for quick access to the fieldnames array
     *
     * first dimension keys are the type constants
     * e.g. CarPeer::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
     */
    protected static $fieldKeys = array (
        BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'VinNumber' => 1, 'Lcdv16' => 2, 'Lcdv32' => 3, 'RegNumber' => 4, 'FirstRegDate' => 5, 'CarMake' => 6, 'ModelVariant' => 7, 'ModelFinishing' => 8, 'GearBox' => 9, 'Outline' => 10, 'CarGenre' => 11, 'DealerCode' => 12, 'DealerName' => 13, 'LastKnownMilage' => 14, 'SysameUpdatedAt' => 15, 'CreatedAt' => 16, 'UpdatedAt' => 17, 'DeletedAt' => 18, ),
        BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'vinNumber' => 1, 'lcdv16' => 2, 'lcdv32' => 3, 'regNumber' => 4, 'firstRegDate' => 5, 'carMake' => 6, 'modelVariant' => 7, 'modelFinishing' => 8, 'gearBox' => 9, 'outline' => 10, 'carGenre' => 11, 'dealerCode' => 12, 'dealerName' => 13, 'lastKnownMilage' => 14, 'sysameUpdatedAt' => 15, 'createdAt' => 16, 'updatedAt' => 17, 'deletedAt' => 18, ),
        BasePeer::TYPE_COLNAME => array (CarPeer::ID => 0, CarPeer::VIN_NUMBER => 1, CarPeer::LCDV_16 => 2, CarPeer::LCDV_32 => 3, CarPeer::REG_NUMBER => 4, CarPeer::FIRST_REG_DATE => 5, CarPeer::CAR_MAKE => 6, CarPeer::MODEL_VARIANT => 7, CarPeer::MODEL_FINISHING => 8, CarPeer::GEAR_BOX => 9, CarPeer::OUTLINE => 10, CarPeer::CAR_GENRE => 11, CarPeer::DEALER_CODE => 12, CarPeer::DEALER_NAME => 13, CarPeer::LAST_KNOWN_MILAGE => 14, CarPeer::SYSAME_UPDATED_AT => 15, CarPeer::CREATED_AT => 16, CarPeer::UPDATED_AT => 17, CarPeer::DELETED_AT => 18, ),
        BasePeer::TYPE_RAW_COLNAME => array ('ID' => 0, 'VIN_NUMBER' => 1, 'LCDV_16' => 2, 'LCDV_32' => 3, 'REG_NUMBER' => 4, 'FIRST_REG_DATE' => 5, 'CAR_MAKE' => 6, 'MODEL_VARIANT' => 7, 'MODEL_FINISHING' => 8, 'GEAR_BOX' => 9, 'OUTLINE' => 10, 'CAR_GENRE' => 11, 'DEALER_CODE' => 12, 'DEALER_NAME' => 13, 'LAST_KNOWN_MILAGE' => 14, 'SYSAME_UPDATED_AT' => 15, 'CREATED_AT' => 16, 'UPDATED_AT' => 17, 'DELETED_AT' => 18, ),
        BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'vin_number' => 1, 'lcdv_16' => 2, 'lcdv_32' => 3, 'reg_number' => 4, 'first_reg_date' => 5, 'car_make' => 6, 'model_variant' => 7, 'model_finishing' => 8, 'gear_box' => 9, 'outline' => 10, 'car_genre' => 11, 'dealer_code' => 12, 'dealer_name' => 13, 'last_known_milage' => 14, 'sysame_updated_at' => 15, 'created_at' => 16, 'updated_at' => 17, 'deleted_at' => 18, ),
        BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, )
    );

    /**
     * Translates a fieldname to another type
     *
     * @param      string $name field name
     * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
     * @param      string $toType   One of the class type constants
     * @return string          translated name of the field.
     * @throws PropelException - if the specified name could not be found in the fieldname mappings.
     */
    public static function translateFieldName($name, $fromType, $toType)
    {
        $toNames = CarPeer::getFieldNames($toType);
        $key = isset(CarPeer::$fieldKeys[$fromType][$name]) ? CarPeer::$fieldKeys[$fromType][$name] : null;
        if ($key === null) {
            throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(CarPeer::$fieldKeys[$fromType], true));
        }

        return $toNames[$key];
    }

    /**
     * Returns an array of field names.
     *
     * @param      string $type The type of fieldnames to return:
     *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
     * @return array           A list of field names
     * @throws PropelException - if the type is not valid.
     */
    public static function getFieldNames($type = BasePeer::TYPE_PHPNAME)
    {
        if (!array_key_exists($type, CarPeer::$fieldNames)) {
            throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
        }

        return CarPeer::$fieldNames[$type];
    }

    /**
     * Convenience method which changes table.column to alias.column.
     *
     * Using this method you can maintain SQL abstraction while using column aliases.
     * <code>
     *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
     *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
     * </code>
     * @param      string $alias The alias for the current table.
     * @param      string $column The column name for current table. (i.e. CarPeer::COLUMN_NAME).
     * @return string
     */
    public static function alias($alias, $column)
    {
        return str_replace(CarPeer::TABLE_NAME.'.', $alias.'.', $column);
    }

    /**
     * Add all the columns needed to create a new object.
     *
     * Note: any columns that were marked with lazyLoad="true" in the
     * XML schema will not be added to the select list and only loaded
     * on demand.
     *
     * @param      Criteria $criteria object containing the columns to add.
     * @param      string   $alias    optional table alias
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function addSelectColumns(Criteria $criteria, $alias = null)
    {
        if (null === $alias) {
            $criteria->addSelectColumn(CarPeer::ID);
            $criteria->addSelectColumn(CarPeer::VIN_NUMBER);
            $criteria->addSelectColumn(CarPeer::LCDV_16);
            $criteria->addSelectColumn(CarPeer::LCDV_32);
            $criteria->addSelectColumn(CarPeer::REG_NUMBER);
            $criteria->addSelectColumn(CarPeer::FIRST_REG_DATE);
            $criteria->addSelectColumn(CarPeer::CAR_MAKE);
            $criteria->addSelectColumn(CarPeer::MODEL_VARIANT);
            $criteria->addSelectColumn(CarPeer::MODEL_FINISHING);
            $criteria->addSelectColumn(CarPeer::GEAR_BOX);
            $criteria->addSelectColumn(CarPeer::OUTLINE);
            $criteria->addSelectColumn(CarPeer::CAR_GENRE);
            $criteria->addSelectColumn(CarPeer::DEALER_CODE);
            $criteria->addSelectColumn(CarPeer::DEALER_NAME);
            $criteria->addSelectColumn(CarPeer::LAST_KNOWN_MILAGE);
            $criteria->addSelectColumn(CarPeer::SYSAME_UPDATED_AT);
            $criteria->addSelectColumn(CarPeer::CREATED_AT);
            $criteria->addSelectColumn(CarPeer::UPDATED_AT);
            $criteria->addSelectColumn(CarPeer::DELETED_AT);
        } else {
            $criteria->addSelectColumn($alias . '.id');
            $criteria->addSelectColumn($alias . '.vin_number');
            $criteria->addSelectColumn($alias . '.lcdv_16');
            $criteria->addSelectColumn($alias . '.lcdv_32');
            $criteria->addSelectColumn($alias . '.reg_number');
            $criteria->addSelectColumn($alias . '.first_reg_date');
            $criteria->addSelectColumn($alias . '.car_make');
            $criteria->addSelectColumn($alias . '.model_variant');
            $criteria->addSelectColumn($alias . '.model_finishing');
            $criteria->addSelectColumn($alias . '.gear_box');
            $criteria->addSelectColumn($alias . '.outline');
            $criteria->addSelectColumn($alias . '.car_genre');
            $criteria->addSelectColumn($alias . '.dealer_code');
            $criteria->addSelectColumn($alias . '.dealer_name');
            $criteria->addSelectColumn($alias . '.last_known_milage');
            $criteria->addSelectColumn($alias . '.sysame_updated_at');
            $criteria->addSelectColumn($alias . '.created_at');
            $criteria->addSelectColumn($alias . '.updated_at');
            $criteria->addSelectColumn($alias . '.deleted_at');
        }
    }

    /**
     * Returns the number of rows matching criteria.
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @return int Number of matching rows.
     */
    public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
    {
        // we may modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(CarPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            CarPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
        $criteria->setDbName(CarPeer::DATABASE_NAME); // Set the correct dbName

        if ($con === null) {
            $con = Propel::getConnection(CarPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        // BasePeer returns a PDOStatement
        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }
    /**
     * Selects one object from the DB.
     *
     * @param      Criteria $criteria object used to create the SELECT statement.
     * @param      PropelPDO $con
     * @return                 Car
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
    {
        $critcopy = clone $criteria;
        $critcopy->setLimit(1);
        $objects = CarPeer::doSelect($critcopy, $con);
        if ($objects) {
            return $objects[0];
        }

        return null;
    }
    /**
     * Selects several row from the DB.
     *
     * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
     * @param      PropelPDO $con
     * @return array           Array of selected Objects
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelect(Criteria $criteria, PropelPDO $con = null)
    {
        return CarPeer::populateObjects(CarPeer::doSelectStmt($criteria, $con));
    }
    /**
     * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
     *
     * Use this method directly if you want to work with an executed statement directly (for example
     * to perform your own object hydration).
     *
     * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
     * @param      PropelPDO $con The connection to use
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     * @return PDOStatement The executed PDOStatement object.
     * @see        BasePeer::doSelect()
     */
    public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(CarPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        if (!$criteria->hasSelectClause()) {
            $criteria = clone $criteria;
            CarPeer::addSelectColumns($criteria);
        }

        // Set the correct dbName
        $criteria->setDbName(CarPeer::DATABASE_NAME);

        // BasePeer returns a PDOStatement
        return BasePeer::doSelect($criteria, $con);
    }
    /**
     * Adds an object to the instance pool.
     *
     * Propel keeps cached copies of objects in an instance pool when they are retrieved
     * from the database.  In some cases -- especially when you override doSelect*()
     * methods in your stub classes -- you may need to explicitly add objects
     * to the cache in order to ensure that the same objects are always returned by doSelect*()
     * and retrieveByPK*() calls.
     *
     * @param      Car $obj A Car object.
     * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
     */
    public static function addInstanceToPool($obj, $key = null)
    {
        if (Propel::isInstancePoolingEnabled()) {
            if ($key === null) {
                $key = (string) $obj->getId();
            } // if key === null
            CarPeer::$instances[$key] = $obj;
        }
    }

    /**
     * Removes an object from the instance pool.
     *
     * Propel keeps cached copies of objects in an instance pool when they are retrieved
     * from the database.  In some cases -- especially when you override doDelete
     * methods in your stub classes -- you may need to explicitly remove objects
     * from the cache in order to prevent returning objects that no longer exist.
     *
     * @param      mixed $value A Car object or a primary key value.
     *
     * @return void
     * @throws PropelException - if the value is invalid.
     */
    public static function removeInstanceFromPool($value)
    {
        if (Propel::isInstancePoolingEnabled() && $value !== null) {
            if (is_object($value) && $value instanceof Car) {
                $key = (string) $value->getId();
            } elseif (is_scalar($value)) {
                // assume we've been passed a primary key
                $key = (string) $value;
            } else {
                $e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Car object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
                throw $e;
            }

            unset(CarPeer::$instances[$key]);
        }
    } // removeInstanceFromPool()

    /**
     * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
     *
     * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
     * a multi-column primary key, a serialize()d version of the primary key will be returned.
     *
     * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
     * @return   Car Found object or null if 1) no instance exists for specified key or 2) instance pooling has been disabled.
     * @see        getPrimaryKeyHash()
     */
    public static function getInstanceFromPool($key)
    {
        if (Propel::isInstancePoolingEnabled()) {
            if (isset(CarPeer::$instances[$key])) {
                return CarPeer::$instances[$key];
            }
        }

        return null; // just to be explicit
    }

    /**
     * Clear the instance pool.
     *
     * @return void
     */
    public static function clearInstancePool($and_clear_all_references = false)
    {
      if ($and_clear_all_references)
      {
        foreach (CarPeer::$instances as $instance)
        {
          $instance->clearAllReferences(true);
        }
      }
        CarPeer::$instances = array();
    }

    /**
     * Method to invalidate the instance pool of all tables related to car
     * by a foreign key with ON DELETE CASCADE
     */
    public static function clearRelatedInstancePool()
    {
    }

    /**
     * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
     *
     * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
     * a multi-column primary key, a serialize()d version of the primary key will be returned.
     *
     * @param      array $row PropelPDO resultset row.
     * @param      int $startcol The 0-based offset for reading from the resultset row.
     * @return string A string version of PK or null if the components of primary key in result array are all null.
     */
    public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
    {
        // If the PK cannot be derived from the row, return null.
        if ($row[$startcol] === null) {
            return null;
        }

        return (string) $row[$startcol];
    }

    /**
     * Retrieves the primary key from the DB resultset row
     * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
     * a multi-column primary key, an array of the primary key columns will be returned.
     *
     * @param      array $row PropelPDO resultset row.
     * @param      int $startcol The 0-based offset for reading from the resultset row.
     * @return mixed The primary key of the row
     */
    public static function getPrimaryKeyFromRow($row, $startcol = 0)
    {

        return (int) $row[$startcol];
    }

    /**
     * The returned array will contain objects of the default type or
     * objects that inherit from the default.
     *
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function populateObjects(PDOStatement $stmt)
    {
        $results = array();

        // set the class once to avoid overhead in the loop
        $cls = CarPeer::getOMClass();
        // populate the object(s)
        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key = CarPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj = CarPeer::getInstanceFromPool($key))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj->hydrate($row, 0, true); // rehydrate
                $results[] = $obj;
            } else {
                $obj = new $cls();
                $obj->hydrate($row);
                $results[] = $obj;
                CarPeer::addInstanceToPool($obj, $key);
            } // if key exists
        }
        $stmt->closeCursor();

        return $results;
    }
    /**
     * Populates an object of the default type or an object that inherit from the default.
     *
     * @param      array $row PropelPDO resultset row.
     * @param      int $startcol The 0-based offset for reading from the resultset row.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     * @return array (Car object, last column rank)
     */
    public static function populateObject($row, $startcol = 0)
    {
        $key = CarPeer::getPrimaryKeyHashFromRow($row, $startcol);
        if (null !== ($obj = CarPeer::getInstanceFromPool($key))) {
            // We no longer rehydrate the object, since this can cause data loss.
            // See http://www.propelorm.org/ticket/509
            // $obj->hydrate($row, $startcol, true); // rehydrate
            $col = $startcol + CarPeer::NUM_HYDRATE_COLUMNS;
        } else {
            $cls = CarPeer::OM_CLASS;
            $obj = new $cls();
            $col = $obj->hydrate($row, $startcol);
            CarPeer::addInstanceToPool($obj, $key);
        }

        return array($obj, $col);
    }

    /**
     * Returns the TableMap related to this peer.
     * This method is not needed for general use but a specific application could have a need.
     * @return TableMap
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function getTableMap()
    {
        return Propel::getDatabaseMap(CarPeer::DATABASE_NAME)->getTable(CarPeer::TABLE_NAME);
    }

    /**
     * Add a TableMap instance to the database for this peer class.
     */
    public static function buildTableMap()
    {
      $dbMap = Propel::getDatabaseMap(BaseCarPeer::DATABASE_NAME);
      if (!$dbMap->hasTable(BaseCarPeer::TABLE_NAME)) {
        $dbMap->addTableObject(new CarTableMap());
      }
    }

    /**
     * The class that the Peer will make instances of.
     *
     *
     * @return string ClassName
     */
    public static function getOMClass($row = 0, $colnum = 0)
    {
        return CarPeer::OM_CLASS;
    }

    /**
     * Performs an INSERT on the database, given a Car or Criteria object.
     *
     * @param      mixed $values Criteria or Car object containing data that is used to create the INSERT statement.
     * @param      PropelPDO $con the PropelPDO connection to use
     * @return mixed           The new primary key.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doInsert($values, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(CarPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        if ($values instanceof Criteria) {
            $criteria = clone $values; // rename for clarity
        } else {
            $criteria = $values->buildCriteria(); // build Criteria from Car object
        }


        // Set the correct dbName
        $criteria->setDbName(CarPeer::DATABASE_NAME);

        try {
            // use transaction because $criteria could contain info
            // for more than one table (I guess, conceivably)
            $con->beginTransaction();
            $pk = BasePeer::doInsert($criteria, $con);
            $con->commit();
        } catch (PropelException $e) {
            $con->rollBack();
            throw $e;
        }

        return $pk;
    }

    /**
     * Performs an UPDATE on the database, given a Car or Criteria object.
     *
     * @param      mixed $values Criteria or Car object containing data that is used to create the UPDATE statement.
     * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
     * @return int             The number of affected rows (if supported by underlying database driver).
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doUpdate($values, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(CarPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $selectCriteria = new Criteria(CarPeer::DATABASE_NAME);

        if ($values instanceof Criteria) {
            $criteria = clone $values; // rename for clarity

            $comparison = $criteria->getComparison(CarPeer::ID);
            $value = $criteria->remove(CarPeer::ID);
            if ($value) {
                $selectCriteria->add(CarPeer::ID, $value, $comparison);
            } else {
                $selectCriteria->setPrimaryTableName(CarPeer::TABLE_NAME);
            }

        } else { // $values is Car object
            $criteria = $values->buildCriteria(); // gets full criteria
            $selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
        }

        // set the correct dbName
        $criteria->setDbName(CarPeer::DATABASE_NAME);

        return BasePeer::doUpdate($selectCriteria, $criteria, $con);
    }

    /**
     * Deletes all rows from the car table.
     *
     * @param      PropelPDO $con the connection to use
     * @return int             The number of affected rows (if supported by underlying database driver).
     * @throws PropelException
     */
    public static function doDeleteAll(PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(CarPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }
        $affectedRows = 0; // initialize var to track total num of affected rows
        try {
            // use transaction because $criteria could contain info
            // for more than one table or we could emulating ON DELETE CASCADE, etc.
            $con->beginTransaction();
            $affectedRows += BasePeer::doDeleteAll(CarPeer::TABLE_NAME, $con, CarPeer::DATABASE_NAME);
            // Because this db requires some delete cascade/set null emulation, we have to
            // clear the cached instance *after* the emulation has happened (since
            // instances get re-added by the select statement contained therein).
            CarPeer::clearInstancePool();
            CarPeer::clearRelatedInstancePool();
            $con->commit();

            return $affectedRows;
        } catch (PropelException $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs a DELETE on the database, given a Car or Criteria object OR a primary key value.
     *
     * @param      mixed $values Criteria or Car object or primary key or array of primary keys
     *              which is used to create the DELETE statement
     * @param      PropelPDO $con the connection to use
     * @return int The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
     *				if supported by native driver or if emulated using Propel.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
     public static function doDelete($values, PropelPDO $con = null)
     {
        if ($con === null) {
            $con = Propel::getConnection(CarPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        if ($values instanceof Criteria) {
            // invalidate the cache for all objects of this type, since we have no
            // way of knowing (without running a query) what objects should be invalidated
            // from the cache based on this Criteria.
            CarPeer::clearInstancePool();
            // rename for clarity
            $criteria = clone $values;
        } elseif ($values instanceof Car) { // it's a model object
            // invalidate the cache for this single object
            CarPeer::removeInstanceFromPool($values);
            // create criteria based on pk values
            $criteria = $values->buildPkeyCriteria();
        } else { // it's a primary key, or an array of pks
            $criteria = new Criteria(CarPeer::DATABASE_NAME);
            $criteria->add(CarPeer::ID, (array) $values, Criteria::IN);
            // invalidate the cache for this object(s)
            foreach ((array) $values as $singleval) {
                CarPeer::removeInstanceFromPool($singleval);
            }
        }

        // Set the correct dbName
        $criteria->setDbName(CarPeer::DATABASE_NAME);

        $affectedRows = 0; // initialize var to track total num of affected rows

        try {
            // use transaction because $criteria could contain info
            // for more than one table or we could emulating ON DELETE CASCADE, etc.
            $con->beginTransaction();

            $affectedRows += BasePeer::doDelete($criteria, $con);
            CarPeer::clearRelatedInstancePool();
            $con->commit();

            return $affectedRows;
        } catch (PropelException $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Validates all modified columns of given Car object.
     * If parameter $columns is either a single column name or an array of column names
     * than only those columns are validated.
     *
     * NOTICE: This does not apply to primary or foreign keys for now.
     *
     * @param      Car $obj The object to validate.
     * @param      mixed $cols Column name or array of column names.
     *
     * @return mixed TRUE if all columns are valid or the error message of the first invalid column.
     */
    public static function doValidate($obj, $cols = null)
    {
        $columns = array();

        if ($cols) {
            $dbMap = Propel::getDatabaseMap(CarPeer::DATABASE_NAME);
            $tableMap = $dbMap->getTable(CarPeer::TABLE_NAME);

            if (! is_array($cols)) {
                $cols = array($cols);
            }

            foreach ($cols as $colName) {
                if ($tableMap->hasColumn($colName)) {
                    $get = 'get' . $tableMap->getColumn($colName)->getPhpName();
                    $columns[$colName] = $obj->$get();
                }
            }
        } else {

        }

        return BasePeer::doValidate(CarPeer::DATABASE_NAME, CarPeer::TABLE_NAME, $columns);
    }

    /**
     * Retrieve a single object by pkey.
     *
     * @param      int $pk the primary key.
     * @param      PropelPDO $con the connection to use
     * @return Car
     */
    public static function retrieveByPK($pk, PropelPDO $con = null)
    {

        if (null !== ($obj = CarPeer::getInstanceFromPool((string) $pk))) {
            return $obj;
        }

        if ($con === null) {
            $con = Propel::getConnection(CarPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $criteria = new Criteria(CarPeer::DATABASE_NAME);
        $criteria->add(CarPeer::ID, $pk);

        $v = CarPeer::doSelect($criteria, $con);

        return !empty($v) > 0 ? $v[0] : null;
    }

    /**
     * Retrieve multiple objects by pkey.
     *
     * @param      array $pks List of primary keys
     * @param      PropelPDO $con the connection to use
     * @return Car[]
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function retrieveByPKs($pks, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(CarPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $objs = null;
        if (empty($pks)) {
            $objs = array();
        } else {
            $criteria = new Criteria(CarPeer::DATABASE_NAME);
            $criteria->add(CarPeer::ID, $pks, Criteria::IN);
            $objs = CarPeer::doSelect($criteria, $con);
        }

        return $objs;
    }

} // BaseCarPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseCarPeer::buildTableMap();

