<?php
// This file generated by Propel 1.6.9 convert-conf target
// from XML runtime conf file /var/www/cron_project/config/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'cron_project' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=cron_project',
        'user' => 'root',
        'password' => 'root',
      ),
    ),
    'default' => 'cron_project',
  ),
  'generator_version' => '1.6.9',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-cron_project-conf.php');
return $conf;