<?php



/**
 * Skeleton subclass for performing query and update operations on the 'user_car' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.9 on:
 *
 * Tue 03 Sep 2013 04:11:15 PM EEST
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.cron_project.model
 */
class UserCarQuery extends BaseUserCarQuery
{
}
